### PR TITLE
Stacking files with GUID names and .transformed extension has issues with some hex editors.

### PR DESCRIPTION
**Pull request by donatas522**
Hello, 
Huge thanks for the project, it helped me to automate the editing of my .hex file.

I noticed that when you do several ModificationTransforms temporary files are stacking in the file directory, which you have to remove later manually, I suggest memorizing previous tempFileName and later removing it using _fileSystem.

Also, I noticed that some editors have issues decoding files that have non .hex extension. They choose depending on it how to decode file. So I suggest to change the output file name.

### CODE REVIEW

**Comment by DerekGn** [comment]
Thanks for the PR, I think there is a bug here, the move operation should have removed the temporary file. So you should only have the transformed file. I will need to investigate why this is happening.

Can you make the change to the file name in a separate PR, If you don't have time I can do it later

**Comment by DerekGn** [comment]
@donatas522 
I have modified the way the extension is generated for the transform. It will keep the same extension as the input file. I will push this shortly to the main branch and build.

**Comment by DerekGn** [comment]
@donatas522 I have updated the code to cleanup files after transform there is an overload of the transform method that you can use. 
The updated version is published to nuget https://www.nuget.org/packages/HexIO/3.0.4

**Comment by donatas522** [comment]
This works, but what about the case if someone calls at least two times ApplyTransforms() with multiple transforms, and one has the default overload set to "false" in order to keep intermediate files? If this is not the last call, tmpFiles will be removed, since ApplyTransforms() removes all files with tmpExtension in directory. That's why I think it's better to remove files only that you have created during one call of ApplyTransforms().

**Comment by DerekGn** [comment]
Then don't use the overload and clean the files yourself. The files where intended for debugging the transformations.

**Comment by DerekGn** [comment]
I will revert the file delete change. I never liked it in the first place it violates single responsibility pattern. It would be better to handle these different use cases in the calling context.

The calling context can decide what to do with the temp files. It really should not be in the transformer class because of reason above.

**Pull request closed without merging**
